services:
  - type: web
    name: faissal-management
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SECRET_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
